[project]
name = "chapter-05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=3.0.4",
    "fastmcp>=2.13.1",
    "feedparser>=6.0.12",
    "requests>=2.32.5",
]
